---
- name: Install Active Directory Domain Services
  win_feature:
    name: AD-Domain-Services
    include_management_tools: true
    include_sub_features: true
    state: present

- name: Install additional features
  win_feature:
    name: "{{ item }}"
    include_management_tools: true
    include_sub_features: true
  loop: "{{ additional_win_features }}"
  when: install_additional_features == true

- name: Setup new Domain
  win_domain:
    dns_domain_name: "{{ ad_domain.name }}"
    safe_mode_password: "{{ ad_domain.dsrm_pass }}"
  register: domain_creation

- name: Reboot if needed
  win_reboot:
    msg: "Rebooting now"
    pre_reboot_delay: 10
  when: domain_creation.reboot_required == true        